name: result_command
description: "A command pattern implementation for Dart and Flutter using result_dart package."
version: 2.1.0
repository: https://github.com/Flutterando/result_command

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  result_dart: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
